#!/usr/bin/env bash
set -euo pipefail

profile_path="/etc/profile.d/sagittarius-juliacall.sh"

julia_exe="${PYTHON_JULIACALL_EXE:-}"
if [ -z "$julia_exe" ]; then
    julia_exe="$(command -v julia)"
fi

julia_project="${PYTHON_JULIACALL_PROJECT:-${PYTHON_JULIAPKG_PROJECT:-}}"
if [ -z "$julia_project" ]; then
    julia_project="$(python - <<'PYPROJECT'
import juliapkg
print(juliapkg.project())
PYPROJECT
)"
fi

julia_bindir="${PYTHON_JULIACALL_BINDIR:-}"
if [ -z "$julia_bindir" ]; then
    julia_bindir="$($julia_exe --startup-file=no -e 'print(Sys.BINDIR)')"
fi

cat > "$profile_path" <<EOF
# Generated by .devcontainer/setup-juliacall-env.sh.
# JuliaCall requires EXE and PROJECT to be set together.
export PYTHON_JULIACALL_EXE="$julia_exe"
export PYTHON_JULIACALL_PROJECT="$julia_project"
export PYTHON_JULIACALL_BINDIR="$julia_bindir"
EOF

chmod 0644 "$profile_path"

echo "Configured JuliaCall environment:"
echo "  PYTHON_JULIACALL_EXE=$julia_exe"
echo "  PYTHON_JULIACALL_PROJECT=$julia_project"
echo "  PYTHON_JULIACALL_BINDIR=$julia_bindir"
